services:
  tododb:
    container_name: tododb
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "my_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql 

  todo.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=tododb,1433;Database=TodoDb;User Id=sa;Password=my_password123;TrustServerCertificate=True;
    depends_on:
      - tododb
    ports:
      - "6000:8080"
      - "6001:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
